version: '3.8'

services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph
    command: serve --location /data --bind 0.0.0.0:7878
    ports:
      - "7878:7878"
    volumes:
      - ./data:/data
    networks:
      - oxigraph_network

  nginx:
    build: 
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "8890:80"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - oxigraph
    networks:
      - oxigraph_network

networks:
  oxigraph_network:
    driver: bridge
