version: '3.8'
services:
  elasticsearch:
    build: .
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net

volumes:
  elasticsearch-data:

networks:
  elastic-net:
    driver: bridge
